workflows:
  expo-build:
    name: Simple Expo APK Build
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.17.0
      npm: 9.6.7
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install Expo CLI and EAS
        script: |
          npm install -g @expo/cli eas-cli
      - name: Set Expo Token
        script: |
          echo "Using Expo token for authentication"
      - name: Try EAS Build
        script: |
          EXPO_TOKEN=$EXPO_TOKEN npx eas build --platform android --profile preview --non-interactive --wait
    artifacts:
      - "*.apk"
      - "*.aab"
    publishing:
      email:
        recipients:
          - caroline@example.com
        notify:
          success: true
          failure: true