workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_credentials
      vars:
        PACKAGE_NAME: "com.petcare.assistant"
      node: 18.17.0
      npm: 9.6.7
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Prebuild for React Native
        script: |
          npx expo prebuild --platform android --clear
      - name: Build APK with Gradle
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - caroline@example.com
        notify:
          success: true
          failure: false