workflows:
  expo-build:
    name: Simple Expo APK Build
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      groups:
        - expo_credentials
      node: 18
      npm: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install Expo CLI and EAS
        script: |
          npm install -g @expo/cli eas-cli
      - name: Expo Login
        script: |
          npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - name: Try EAS Build
        script: |
          npx eas build --platform android --profile preview --non-interactive --wait
    artifacts:
      - "*.apk"
      - "*.aab"
    publishing:
      email:
        recipients:
          - caroline@example.com
        notify:
          success: true
          failure: true