workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.petcare.assistant"
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.17.0
      npm: 9.6.7
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Login to Expo
        script: |
          echo "Logging in to Expo..."
          # Use environment variable for token if available
      - name: Build APK with EAS
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
    publishing:
      email:
        recipients:
          - caroline@example.com
        notify:
          success: true
          failure: false