export const themes = {
  pink: {
    id: 'pink',
    name: 'Pink Dream',
    primary: '#FF6B9D',
    primaryLight: '#FFE1EC',
    secondary: '#C7A5C4',
    background: '#FFF5F8',
    surface: '#FFFFFF',
    success: '#4CAF50',
    successLight: '#E8F5E8',
    warning: '#FFC107',
    warningLight: '#FFF3CD',
    error: '#FF4757',
    errorLight: '#FFE8E8',
    text: '#333333',
    textLight: '#8E7A8B',
    border: '#FFE1EC',
  },
  blue: {
    id: 'blue',
    name: 'Ocean Blue',
    primary: '#2196F3',
    primaryLight: '#E3F2FD',
    secondary: '#90CAF9',
    background: '#F3F9FF',
    surface: '#FFFFFF',
    success: '#4CAF50',
    successLight: '#E8F5E8',
    warning: '#FFC107',
    warningLight: '#FFF3CD',
    error: '#F44336',
    errorLight: '#FFEBEE',
    text: '#333333',
    textLight: '#666666',
    border: '#BBDEFB',
  },
  purple: {
    id: 'purple',
    name: 'Royal Purple',
    primary: '#9C27B0',
    primaryLight: '#F3E5F5',
    secondary: '#CE93D8',
    background: '#FAF4FB',
    surface: '#FFFFFF',
    success: '#4CAF50',
    successLight: '#E8F5E8',
    warning: '#FFC107',
    warningLight: '#FFF3CD',
    error: '#E91E63',
    errorLight: '#FCE4EC',
    text: '#333333',
    textLight: '#7B1FA2',
    border: '#E1BEE7',
  },
  green: {
    id: 'green',
    name: 'Nature Green',
    primary: '#4CAF50',
    primaryLight: '#E8F5E8',
    secondary: '#81C784',
    background: '#F1F8E9',
    surface: '#FFFFFF',
    success: '#2E7D32',
    successLight: '#E8F5E8',
    warning: '#FFC107',
    warningLight: '#FFF3CD',
    error: '#F44336',
    errorLight: '#FFEBEE',
    text: '#333333',
    textLight: '#388E3C',
    border: '#C8E6C9',
  },
  orange: {
    id: 'orange',
    name: 'Sunset Orange',
    primary: '#FF9800',
    primaryLight: '#FFF3E0',
    secondary: '#FFCC02',
    background: '#FFF8F0',
    surface: '#FFFFFF',
    success: '#4CAF50',
    successLight: '#E8F5E8',
    warning: '#FF8F00',
    warningLight: '#FFF3CD',
    error: '#F44336',
    errorLight: '#FFEBEE',
    text: '#333333',
    textLight: '#F57C00',
    border: '#FFCC80',
  },
  red: {
    id: 'red',
    name: 'Cherry Red',
    primary: '#F44336',
    primaryLight: '#FFEBEE',
    secondary: '#EF5350',
    background: '#FFF5F5',
    surface: '#FFFFFF',
    success: '#4CAF50',
    successLight: '#E8F5E8',
    warning: '#FFC107',
    warningLight: '#FFF3CD',
    error: '#D32F2F',
    errorLight: '#FFCDD2',
    text: '#333333',
    textLight: '#C62828',
    border: '#FFCDD2',
  },
};

export const themeOptions = [
  { id: 'pink', name: '💖 Pink Dream', color: '#FF6B9D' },
  { id: 'blue', name: '💙 Ocean Blue', color: '#2196F3' },
  { id: 'purple', name: '💜 Royal Purple', color: '#9C27B0' },
  { id: 'green', name: '💚 Nature Green', color: '#4CAF50' },
  { id: 'orange', name: '🧡 Sunset Orange', color: '#FF9800' },
  { id: 'red', name: '❤️ Cherry Red', color: '#F44336' },
];

export const getTheme = (themeId) => {
  return themes[themeId] || themes.pink;
};